##Spring Configuration
server:
  port: 8081
spring:
  application:
    name: CrediYa_Applications
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
  adapters:
    mariadb:
      database: "crediya_applications"
      host: "localhost"
      port: 3306
      username: "crediya_user"
      password: "crediya123"
      pool:
        initial-size: 12
        max-size: 15
        max-idle-time: 10
